### ISSUE TITLE
到模拟器上后打开程序闪退，运行信息如下

### ISSUE THREAD

**Issue by Shunxiaochuan** [DJI-Mobile-SDK-Tutorials/Android-ImportAndActivateSDKInAndroidStudio#13]
11/06 14:35:29: Launching 'ImportSDKDemo-app' on Nexus 6P API 29.
$ adb shell am start -n "com.dji.importSDKDemo/com.dji.importSDKDemo.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Waiting for process to come online...
Connected to process 5257 on device 'Nexus_6P_API_29 [emulator-5554]'.
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
I/i.importSDKDem: Not late-enabling -Xcheck:jni (already on)
E/i.importSDKDem: Unknown bits set in runtime_flags: 0x8000
W/i.importSDKDem: Unexpected CPU variant for X86 using defaults: x86
I/i.importSDKDem: The ClassLoaderContext is a special shared library.
I/i.importSDKDem: The ClassLoaderContext is a special shared library.
W/i.importSDKDem: Accessing hidden field Ldalvik/system/BaseDexClassLoader;->pathList:Ldalvik/system/DexPathList; (greylist, reflection, allowed)
W/i.importSDKDem: Accessing hidden method Ldalvik/system/DexPathList;->makeInMemoryDexElements([Ljava/nio/ByteBuffer;Ljava/util/List;)[Ldalvik/system/DexPathList$Element; (greylist, JNI, allowed)
W/i.importSDKDem: Accessing hidden field Ldalvik/system/DexPathList;->dexElements:[Ldalvik/system/DexPathList$Element; (greylist, reflection, allowed)
D/libEGL: Emulator has host GPU support, qemu.gles is set to 1.
W/libc: Unable to set property "qemu.gles" to "1": connection failed; errno=13 (Permission denied)
W/RenderThread: type=1400 audit(0.0:17): avc: denied { write } for name="property_service" dev="tmpfs" ino=7388 scontext=u:r:untrusted_app_27:s0:c133,c256,c512,c768 tcontext=u:object_r:property_socket:s0 tclass=sock_file permissive=0 app=com.dji.importSDKDemo
D/libEGL: loaded /vendor/lib/egl/libEGL_emulation.so
D/libEGL: loaded /vendor/lib/egl/libGLESv1_CM_emulation.so
D/libEGL: loaded /vendor/lib/egl/libGLESv2_emulation.so
W/i.importSDKDem: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (greylist, reflection, allowed)
W/i.importSDKDem: Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (greylist, reflection, allowed)
D/HostConnection: HostConnection::get() New Host Connection established 0xdef80180, tid 5337
D/HostConnection: HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_3_1 
W/OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
D/EGL_emulation: eglCreateContext: 0xebdb6340: maj 3 min 1 rcv 4
D/EGL_emulation: eglMakeCurrent: 0xebdb6340: ver 3 1 (tinfo 0xebda3ca0)
E/eglCodecCommon: glUtilsParamSize: unknow param 0x000082da
    glUtilsParamSize: unknow param 0x000082da
W/Gralloc3: mapper 3.x is not supported
D/HostConnection: createUnique: call
    HostConnection::get() New Host Connection established 0xdef81940, tid 5337
D/HostConnection: HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_3_1 
D/eglCodecCommon: allocate: Ask for block of size 0x1000
    allocate: ioctl allocate returned offset 0x3ffff4000 size 0x2000
D/EGL_emulation: eglMakeCurrent: 0xebdb6340: ver 3 1 (tinfo 0xebda3ca0)
I/i.importSDKDem: Background young concurrent copying GC freed 10420(4377KB) AllocSpace objects, 3(11MB) LOS objects, 81% free, 1368KB/7512KB, paused 7.577ms total 142.037ms
D/EGL_emulation: eglMakeCurrent: 0xebdb6340: ver 3 1 (tinfo 0xebda3ca0)
D/EGL_emulation: eglMakeCurrent: 0xebdb6340: ver 3 1 (tinfo 0xebda3ca0)
D/EGL_emulation: eglMakeCurrent: 0xebdb6340: ver 3 1 (tinfo 0xebda3ca0)
D/EGL_emulation: eglMakeCurrent: 0xebdb6340: ver 3 1 (tinfo 0xebda3ca0)
E/linker: "/data/app/com.dji.importSDKDemo-ZuHeQHAAq7Epn-lEnpP6Uw==/lib/x86/libffmpeg.so" has text relocations (https://android.googlesource.com/platform/bionic/+/master/android-changes-for-ndk-developers.md#Text-Relocations-Enforced-for-API-level-23)
D/EGL_emulation: eglMakeCurrent: 0xebdb6340: ver 3 1 (tinfo 0xebda3ca0)
W/System.err: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/com.dji.importSDKDemo-ZuHeQHAAq7Epn-lEnpP6Uw==/lib/x86/libffmpeg.so" has text relocations (https://android.googlesource.com/platform/bionic/+/master/android-changes-for-ndk-developers.md#Text-Relocations-Enforced-for-API-level-23)
W/System.err:     at java.lang.Runtime.loadLibrary0(Runtime.java:1071)
W/System.err:     at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
        at java.lang.System.loadLibrary(System.java:1667)
        at dji.midware.natives.SDKRelativeJNI.<clinit>(Unknown Source:6)
        at dji.midware.natives.SDKRelativeJNI.native_getUsbAccessoryAttachedString(Native Method)
        at dji.sdk.sdkmanager.DJISDKManager.<clinit>(Unknown Source:32)
        at dji.sdk.sdkmanager.DJISDKManager.getInstance(Unknown Source:0)
        at com.dji.importSDKDemo.MainActivity$1.run(Unknown Source:7)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
D/SDKRelativeJNI: Couldn't load lib
E/i.importSDKDem: No implementation found for java.lang.String dji.midware.natives.SDKRelativeJNI.native_getUsbAccessoryAttachedString() (tried Java_dji_midware_natives_SDKRelativeJNI_native_1getUsbAccessoryAttachedString and Java_dji_midware_natives_SDKRelativeJNI_native_1getUsbAccessoryAttachedString__)
E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
    Process: com.dji.importSDKDemo, PID: 5257
    java.lang.UnsatisfiedLinkError: No implementation found for java.lang.String dji.midware.natives.SDKRelativeJNI.native_getUsbAccessoryAttachedString() (tried Java_dji_midware_natives_SDKRelativeJNI_native_1getUsbAccessoryAttachedString and Java_dji_midware_natives_SDKRelativeJNI_native_1getUsbAccessoryAttachedString__)
        at dji.midware.natives.SDKRelativeJNI.native_getUsbAccessoryAttachedString(Native Method)
        at dji.sdk.sdkmanager.DJISDKManager.<clinit>(Unknown Source:32)
        at dji.sdk.sdkmanager.DJISDKManager.getInstance(Unknown Source:0)
        at com.dji.importSDKDemo.MainActivity$1.run(Unknown Source:7)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
I/Process: Sending signal. PID: 5257 SIG: 9
Process 5257 terminated.

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/40817'>Zendesk ticket #40817</a>:<br><br>尊敬的用户，

 您好！感谢您联系DJI 大疆创新。
抱歉，MSDK不支持安卓模拟器运行，需要使用实机。

非常感谢您的理解与配合，祝您生活愉快！

Best Regards,

DJI 大疆创新SDK技术支持
